### ISSUE TITLE
doesn't work on images

### ISSUE THREAD

**Issue by traktori** [TheAMM/mpv_crop_script#1]
It's a great script and works great on videos, but I'm trying to switch to mpv as my main image viewer and it fails when I try to crop an image. it gives me an error that says
`[osd/libass] Glyph bounding box too large: -67108863x-67108863px`

**Comment by TheAMM** [comment]
What version are you on, and what exactly happens? That libass warning should not matter, it happens from time to time, but doesn't affect the script. Cropping images works for me, but since I don't know which version you are on or how it "fails" (nothing should kill the script), I'm guessing here.
Encoding is also a bit broken on recent mpv versions, but wm4 has a branch with fixes, likely merged soonish.

Try adding a `--oneverdrop` in the mpv command table and report back:
```lua
  local cmd = {
    args = {
    "mpv", output_path_full,
    "--vf=crop=" .. crop_string,
    "--frames=1", "--ovc=png",
    "--oneverdrop", -- This here
    "-o", output_path
    }
  }
```

**Comment by TheAMM** [comment]
Does `mpv --ovc=help` have `png` in the output?
```
  --ovc=png          PNG (Portable Network Graphics) image
```
Is the directory your filename template `output_template` points to writeable?
Also try setting `keep_original=yes` in your script conf and take a look at the full-size screenshot, if it looks corrupt.

**Comment by TheAMM** [comment]
No problem. I'll add some warnings for that, later.
