### ISSUE TITLE
Add extension/original_extension to property list

### ISSUE THREAD

**Issue by Dupond** [TheAMM/mpv_crop_script#3]
Hello,
I use your script to crop images (I use mpv as my image viewer, since it has all the options I need, and I don't have to install one more package)... and maybe I'm not the only one ;)
So if the file that I crop is an image, being able to use the original extension would be nice.
Something like : `output_template_image=./${filename}.${extension}` in the mpv_crop_script.conf file.
Thanx in advance !
Best regards,
Dupond

**Comment by TheAMM** [comment]
I've been planning to add the `${extension}` to mitigate against users who forget to add the extension, but I don't really like saving images with the original extension. mpv is not guaranteed to support everything, and then you have stuff like apng (this shouldn't be saved as apng, because it's a single cropped frame!), gif (animation as well, but also indexed colors!), and all the lossy formats (lossy to lossless is a sin, but lossy to lossy is worse than that) - PNG is a safe bet, a lossless well-supported format.

I'll add the `extension` and `original_extension` to the property pool when I get around to it, but I won't match the original image format - mpv will still be passed `--ovc=png`. You may remove the line from your copy of the script and rely on mpv/ffmpeg autodetecting the format, though.

**Comment by TheAMM** [comment]
On second look I already did have it there, as `file_ext`. Hmh.

**Comment by Dupond** [comment]
Hello,
Thanx for taking care. "Editing my copy of the script" is far from ideal though, since the modifications will be overwritten each time you update the script.
Is `$file_ext` the original extension of the file ? But what if the file is a movie and not an image ? That's why I was suggesting to have `output_template` if the file is a movie, and `output_template_image` if it's an image... or am I misunderstanding something ?

**Comment by TheAMM** [comment]
You can use `.${?mpv/duration:${ext}}${!mpv/duration:${file_ext}}` to expand into the user-set extension if the current file has a non-zero duration, and to the original extension if it lacks duration. No need for multiple templates.
I'll add an `is_image` on the next release to make it clearer, though. Also, currently `file_ext` suffers from a copypaste error, so you'll have to wait until the next release before it'll work as expected.

**Comment by Dupond** [comment]
I just wanted to let you know that it works just fine with the 0.4.1 release, and to thank you for it.
For those who could be interested, you can know have the following output_template setting to use the original extension when the file is an image :
`output_template=${filename}.${?is_image:${file_ext}}${!is_image:${ext}}`
I personally put `./` before `${filename}` to save the cropped image in the same folder as the original file, but this will be a problem if the file is a streaming, and you clearly state that "relative paths are mostly untested". So maybe it would be useful to provide some information in README.md about the default location where the cropped file will be saved if no path is given in `output_template` ? (eg. what will happen if you have : `output_template=${filename}.${ext}` ?)

**Comment by TheAMM** [comment]
Paths are relative to the current working directory (not by design, but by default). `./` does not do anything, it's redundant. The property expander does not handle environment variables or the tilde and are unsupported.
I say that relative paths are unsupported exactly because I don't offer any support for them. If the user is advanced enough to understand what relative paths mean, then they are free to use them. But especially on Windows, the CWD can vary wildly depending on how you launch mpv, and therefore relative paths are not something casual users should start poking at.
